// UserPlantCareEvents.jsx - Hiển thị và quản lý lịch sử chăm sóc theo chế độ editable/read-only
import { useCallback, useEffect, useState } from "react";
import { Loader2, Pencil, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { createCareEvent, deleteCareEvent, getCareEvents, updateCareEvent } from "../api";
import { getApiErrorMessage } from "../myGarden.utils";
const TYPES = { watering: "Tưới nước", fertilizing: "Bón phân", pruning: "Cắt tỉa", repotting: "Thay chậu", treatment: "Điều trị", observation: "Quan sát" };
const emptyForm = () => ({ type: "watering", performedAt: new Date().toISOString().slice(0, 16), notes: "" });
export function UserPlantCareEvents({ userPlantId, readOnly = false }) {
  const [events, setEvents] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [form, setForm] = useState(null); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await getCareEvents(userPlantId); setEvents(response.data || []); } catch (requestError) { setError(getApiErrorMessage(requestError, "Không thể tải lịch sử chăm sóc.")); } finally { setLoading(false); } }, [userPlantId]);
  useEffect(() => { if (userPlantId) load(); }, [userPlantId, load]);
  const save = async (event) => { event.preventDefault(); setSaving(true); try { const payload = { type: form.type, performedAt: new Date(form.performedAt).toISOString(), notes: form.notes }; const response = form._id ? await updateCareEvent(userPlantId, form._id, payload) : await createCareEvent(userPlantId, payload); setEvents((current) => form._id ? current.map((item) => item._id === form._id ? response.data : item) : [response.data, ...current]); setForm(null); toast.success("Đã lưu lịch sử chăm sóc."); } catch (requestError) { toast.error(getApiErrorMessage(requestError, "Không thể lưu lịch sử.")); } finally { setSaving(false); } };
  const remove = async (eventId) => { if (!window.confirm("Xóa bản ghi chăm sóc này?")) return; try { await deleteCareEvent(userPlantId, eventId); setEvents((current) => current.filter((item) => item._id !== eventId)); toast.success("Đã xóa bản ghi."); } catch (requestError) { toast.error(getApiErrorMessage(requestError, "Không thể xóa bản ghi.")); } };
  return <section className="space-y-3 rounded-xl border p-4"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Lịch sử chăm sóc</h3><p className="text-xs text-muted-foreground">Hoạt động thực tế của cây</p></div>{!readOnly && <Button type="button" size="sm" onClick={() => setForm(emptyForm())}><Plus className="mr-1 h-4 w-4" />Thêm</Button>}</div>{form && !readOnly ? <form className="grid gap-2 rounded-lg bg-muted/40 p-3 sm:grid-cols-2" onSubmit={save}><select className="rounded-md border bg-background p-2" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}>{Object.entries(TYPES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input className="rounded-md border bg-background p-2" type="datetime-local" value={form.performedAt} onChange={(e) => setForm({ ...form, performedAt: e.target.value })} required /><textarea className="sm:col-span-2 rounded-md border bg-background p-2" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} placeholder="Ghi chú" /><div className="sm:col-span-2 flex gap-2"><Button type="submit" size="sm" disabled={saving}>{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : "Lưu"}</Button><Button type="button" size="sm" variant="outline" onClick={() => setForm(null)}>Hủy</Button></div></form> : null}{loading ? <p className="text-sm text-muted-foreground">Đang tải...</p> : error ? <p className="text-sm text-destructive">{error}</p> : events.length === 0 ? <p className="rounded-lg bg-muted/40 p-3 text-sm text-muted-foreground">Chưa có lịch sử chăm sóc.</p> : <div className="space-y-2">{events.map((item) => <div key={item._id} className="flex gap-3 rounded-lg border p-3"><div className="min-w-0 flex-1"><p className="font-medium">{TYPES[item.type]}</p><p className="text-xs text-muted-foreground">{new Date(item.performedAt).toLocaleString("vi-VN")}</p>{item.notes ? <p className="mt-1 whitespace-pre-wrap text-sm">{item.notes}</p> : null}</div>{!readOnly && <div className="flex gap-1"><Button type="button" size="icon" variant="ghost" onClick={() => setForm({ ...item, performedAt: new Date(item.performedAt).toISOString().slice(0, 16) })}><Pencil className="h-4 w-4" /></Button><Button type="button" size="icon" variant="ghost" className="text-destructive" onClick={() => remove(item._id)}><Trash2 className="h-4 w-4" /></Button></div>}</div>)}</div>}</section>;
}
